buildscript {
    repositories {
        maven { url 'https://maven.minecraftforge.net' }
        maven { url 'https://repo.spongepowered.org/maven' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '2.0.4'
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

version = '0.2.1'
group = 'redfoxexpand'
archivesBaseName = 'RedFoxExpand-1.8.9'

sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
compileJava.options.encoding = 'UTF-8'

minecraft {
    version = '1.8.9-11.15.1.2318-1.8.9'
    runDir = 'run'
    mappings = 'stable_22'
    makeObfSourceJar = false
}

repositories {
    maven { url 'https://repo.spongepowered.org/maven' }
    mavenCentral()
}

configurations {
    shade
    compile.extendsFrom(shade)
}

dependencies {
    shade('org.spongepowered:mixin:0.7.11-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
        exclude module: 'log4j-core'
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand version: project.version, mcversion: project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

sourceSets.main.ext.refMap = 'mixins.redfoxexpand.refmap.json'

jar {
    classifier = 'slim'
    manifest.attributes(
        'FMLCorePlugin': 'redfoxexpand.mixin.RedFoxExpandMixinLoader',
        'ForceLoadAsMod': true,
        'FMLCorePluginContainsFMLMod': true,
        'ModSide': 'CLIENT',
        'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
        'TweakOrder': 0,
        'MixinConfigs': 'mixins.redfoxexpand.json'
    )
}

shadowJar {
    classifier = ''
    configurations = [project.configurations.shade]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest.inheritFrom jar.manifest
}

reobf {
    shadowJar {}
}

build.dependsOn reobfShadowJar

task prepareRelease(type: Copy, dependsOn: build) {
    description = 'Copies the reobfuscated Shadow JAR into release/.'
    group = 'distribution'
    from "$buildDir/libs/${archivesBaseName}-${version}.jar"
    into "$projectDir/release"
}
